name: Build Windows EXE

on:
  push:
    branches:
      - main  # Runs the workflow when you push to the main branch
  workflow_dispatch:  # Allows manual runs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas pywin32

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico dns_updater.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dns-updater-exe
          path: dist/dns_updater.exe
