name: Build and Package Frontend & Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows to support PyInstaller EXE build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Step 1: Set up Node.js for Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 🔹 Step 2: Install & Build React Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          mv build ../backend/frontend  # Move build to backend folder

      # 🔹 Step 3: Set up Python for Backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 🔹 Step 4: Install Python Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔹 Step 5: Package Backend (with Frontend) into a Single EXE
      - name: Build Single EXE
        run: |
          cd backend
          pyinstaller --onefile --windowed --add-data "frontend;frontend" --icon=icon.ico backend.py

      # 🔹 Step 6: Upload EXE Artifact
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-app-exe
          path: backend/dist/backend.exe  # Path to final EXE
