name: Build DNS Updater

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Set up environment variables and paths
    - name: Set environment variables and paths
      run: |
        # Add Python Scripts to PATH
        $env:Path = "C:\hostedtoolcache\windows\Python\3.13.2\x64\Scripts;$env:Path"
        
        # Add Qt to PATH (assuming installed via winget or pre-installed location)
        $env:Path = "C:\Qt\5.15.4\mingw81_64\bin;$env:Path"
        
        Write-Host "Current PATH: $env:Path"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Copy Icon to Build Directory
    - name: Copy Icon to Build Directory
      run: |
        mkdir -p dist/img
        cp img/icon.ico dist/img/

    # Build the executable
    - name: Build the executable
      run: |
        pyinstaller --onefile --windowed --icon=dist/img/icon.ico src/dns_updater_gui.py

    # Upload executable
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dns_updater-exe
        path: dist/DNS_Updater.exe
